name: 'SSH My Action'
description: 'Execute command via SSH'
author: 'gumelar@gpted.com'
inputs:
  USER:
    description: 'SSH username'
    default: 'root'
    required: false
  HOST:
    description: 'SSH host'
    required: true
  PORT:
    description: 'SSH port'
    default: '22'
    required: false
  PRIVATE_KEY:
    description: 'SSH private key'
    required: true
  CMD:
    description: 'Command to be executed'
    required: true
    default: 'echo "$(whoami)" login at $(date) from Github Action!'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: "black"
  icon: "anchor"
