name: test
on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH My Action
        uses: GPTED/SSH-My-Action@feature
        with:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}